# this is name of workflow that will be displaed in Actions tab
name: CICD 

# Manual click (deliver) workflow wheneven user need
on :
   workflow_dispatch: 
      inputs:
         enviroment:
            description: This is the enviroment value where this workflow runs
            default: 'dev' 
            required: true
            type: choice
            options:
               - dev
               - prod
               - staging

jobs:

   code:
      runs-on: ubuntu-latest
      steps:
         - name: checkout code
           run: echo "code clone from github"

   build:
      needs: [code]
      runs-on: ubuntu-latest
      steps:
       - name: Build docker Container
         run: echo "Dcoker container build"

   test:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
       - name: Test the container
         run: echo "Testing the container"

   deploy:
      if: inputs.enviroment == 'dev'
      needs: [build, test]
      runs-on: ubuntu-latest
      steps:
         - name: Deploy the Container
           run: echo "deploy the app using docker compose"



           
